### ISSUE TITLE
Extract the random generator into a separate package?

### ISSUE THREAD

**Issue by kirbysayshi** [blixt/js-procedural#3]
It would be nice to have it separately, it's one of the most concise random generators I've seen :)

**Comment by blixt** [comment]
Done: https://www.npmjs.com/package/arbit

**Comment by kirbysayshi** [comment]
![kirbyending](https://cloud.githubusercontent.com/assets/90831/8398743/83b235b2-1dc9-11e5-8c91-1a59d7443941.jpg)

INCREDIBLE
